name: Publish
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    uses: Lepinoid/WorkflowCollections/.github/workflows/publish_to_maven-repo.yml@main
    with:
      java_version: 11
    secrets: inherit